Update workflow.yml

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -13,19 +13,31 @@ jobs:
     runs-on: ubuntu-latest
     container: python:3.9-slim
     steps:
-      - name: Checkout
+      - name: Checkout Código
         uses: actions/checkout@v3
-      
-      - name: Install dependencies
+
+      - name: Debug - Verificar archivos en el entorno
+        run: ls -R
+
+      - name: Verificar si requirements.txt existe
+        run: |
+          if [ -f requirements.txt ]; then
+            echo "✅ requirements.txt encontrado"
+          else
+            echo "❌ Error: requirements.txt no encontrado"
+            exit 1
+          fi
+
+      - name: Instalar dependencias
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
       
-      - name: Lint with flake8
+      - name: Lint con flake8
         run: |
           flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
           flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
       
-      - name: Run unit tests with nose
+      - name: Ejecutar pruebas unitarias con nose
         run: |
           nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
